In [36]:
import numpy.linalg as linalg
import numpy as np

## Дурын матрицын Онцгой Утгын Задралыг авч үзэе. 

In [37]:
A = np.random.randn(3, 4) 

Өгөгдсөн матриц нь:

In [38]:
print(A)

[[-0.79164636  0.00898644  0.66668641 -0.80577924]
 [ 0.18219955  0.04515089 -0.31628269  1.64914704]
 [ 0.62033301 -0.54341104 -0.87410559 -0.67716419]]


Тэгвэл матриц $ A=Q_1 \Sigma Q_2^T$ нь:

In [42]:
Q1, Sigma, Q2_T = linalg.svd(A, full_matrices=True)

In [43]:
print(Q1)

[[ 0.54737268  0.4417076  -0.71082877]
 [-0.82363009  0.13373172 -0.55113455]
 [ 0.14837997 -0.88713597 -0.43700476]]


In [44]:
print(Sigma)

[2.02712881 1.51045362 0.29578851]


In [45]:
print(Q2_T)

[[-0.24238501 -0.05569454  0.24454594 -0.93720057]
 [-0.57971332  0.32578754  0.68034789  0.30809365]
 [ 0.64647565  0.69712368  0.27858668 -0.13593115]
 [-0.43272533  0.63622259 -0.63222899 -0.09086318]]
